# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('state', models.CharField(max_length=30, verbose_name='State')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('place_type', models.IntegerField(choices=[(10, 'Coffee Shop'), (20, 'Restaurant'), (30, 'Coworking'), (40, 'Bookstore'), (0, 'Other')])),
            ],
            options={
                'verbose_name_plural': 'Places',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internet', models.IntegerField(verbose_name='Internet')),
                ('food', models.IntegerField(verbose_name='Food')),
                ('customer_service', models.IntegerField(verbose_name='Customer Service')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('comfort', models.IntegerField(verbose_name='Comfort')),
                ('noise', models.IntegerField(verbose_name='Noise')),
                ('overall', models.IntegerField(verbose_name='Overall Rating')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Place')),
            ],
        ),
    ]
