# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170805_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetrating',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Password'),
        ),
    ]
