# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 10:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170805_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ('-created',), 'verbose_name': 'Rating'},
        ),
        migrations.AlterField(
            model_name='internetrating',
            name='speed',
            field=models.IntegerField(blank=True, choices=[(1, 'Less than 1 Mbps'), (3, 'Between 1 and 3 Mbps'), (5, 'Between 3 and 5 Mbps'), (10, 'Between 5 and 10 Mbps'), (20, 'Between 10 and 20 Mbps'), (50, 'Between 20 and 50 Mbps'), (100, 'Between 50 and 100 Mbps'), (1000, 'More than 100 Mbps')], null=True, verbose_name='Speed'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.IntegerField(choices=[(10, 'Coffee Shop'), (20, 'Restaurant'), (30, 'Coworking'), (40, 'Bookstore'), (0, 'Other')], verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='comfort',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Comfort'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='customer_service',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Customer Service'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='noise',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Noise'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='overall',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Overall Rating'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Price'),
        ),
    ]
