version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    environment:
      CODECOV_TOKEN: 972d6afa-92b8-4fcb-9d89-ce1cc37782b6
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-dev.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            coverage run manage.py test
            coverage xml
            coverage report -m
      - store_artifacts:
          path: test-reports
          destination: test-reports
      - run: |
          . venv/bin/activate
          codecov --token=$CODECOV_TOKEN
